### ISSUE TITLE
Brazil - Design data grid

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#1]

**Comment by LauraReynal** [comment]
https://docs.google.com/document/d/1SAWkekR5zeKHN1xSpSM043FpVVvKUk_o2Kl4PiJK4N8/edit?usp=sharing

@sabrinang @thisandagain The grid which needs work is available in this document

How do we integrate footnotes?

**Comment by sabrinang** [comment]
I edited the graph: https://www.dropbox.com/s/v7yk87aj4pboi9u/BrazilTable1902.pdf?dl=0
Dropbox Folder: Research/MWC Synthesis/BrazilTable1902.pdf

Let me know if it needs to match specific colours in the Brazil report or any other feedback you may have.

**Comment by LauraReynal** [comment]
Thanks @sabrinang :smile: I think its good !
Im inserting them in the report now.
