### ISSUE TITLE
Get Business introduction letter for India visa 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#102]
For me (UK requirements)

A letter of introduction from the applicant's UK employer. A copy is accepted. This letter must:

    Be addressed to:"The Indian High Commission, India House, Aldwych, London, WC2B 4NA"
    Be on company letterhead paper with the name and address matching exactly to that which is stated on the visa form
    Include the applicant's full name as stated in their passport
    Include the passport number of the applicant
    Include the date of issue of the passport
    Include the date of expiry of the passport
    Specify the purpose of journey
    Specify the exact nature of the business being conducted
    Include the name of the organisation(s) to be visited
    Specify the requested number of entries and the length of visa required
    Include an acceptance of financial responsibility for the applicant
    Be signed by the applicant's supervisor or the company's HR department

@secretrobotron check out your requirements too!

**Comment by secretrobotron** [comment]
@LauraReynal let's print these to take with us.
Otherwise, done.
