### ISSUE TITLE
Laura and Bobby to High Five

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/research#104]
Just coming back from PTO and catching up on all my github mail. DAMN you guys have been busy. Nice work @LauraReynal and @secretrobotron for filling up this repo with relevant and meaningful work! :hand:

**Comment by LauraReynal** [comment]
Woop Woop 
thanks @cassiemc for the nice words :heart: :fish: :fish_cake: :tropical_fish: :heartpulse:

**Comment by secretrobotron** [comment]
:boom: :boom: :boom:
:boom: :clap: :boom:
:boom: :boom: :boom:

**Comment by secretrobotron** [comment]
Actually, what's the ETA on this? My hand is ready for so many fives (low or high).

**Comment by cassiemc** [comment]
I added a new milestone. It's critical we meet this date.

**Comment by secretrobotron** [comment]
Verified complete in Orlando. Good job, team.
