### ISSUE TITLE
Design Research Website MVP

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/research#105]
From phase 1 of https://github.com/MozillaFoundation/research/issues/77

Based on wireframes https://redpen.io/p/oj84c5335720112e06 (but without web journey section)

Copy (in progress) and images are here: https://docs.google.com/a/mozilla.com/document/d/1ZkURIpLedt7lSBtbWv9TTqOGYo9lCwFdbtAUoieWHQw/edit?usp=sharing

cc @secretrobotron @simonwex

**Comment by kristinashu** [comment]
Here's where I'm at with the comps: https://redpen.io/p/opdb303c31041d13b6

@LauraReynal @secretrobotron @simonwex @cassiemc let me know if you have any feedback.

**Comment by LauraReynal** [comment]
@kristinashu it is gorgeous :heart: :cat: :tropical_fish: 

Thank you !

**Comment by secretrobotron** [comment]
Yep! That looks amazing.

I can shorten all of the copy to match the limit that appears in the redpen.

**Comment by secretrobotron** [comment]
Took a first stab at making it HTML: http://secretrobotron.github.io/research-website/

@kristinashu looks like you processed these images a bit. Can you share?

**Comment by kristinashu** [comment]
@secretrobotron sweet! Do you have illustrator? All my working files are here if you want to take a look https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLRzVCVU9GQndCMHc&usp=sharing

I mocked up the site for a bunch of different widths (I was thinking the site would be full width and need to resize for different browsers but let know what you think). 

I'm saving out the images now.

**Comment by kristinashu** [comment]
Here are all the cropped images https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLV01fNWhCeTlIODg&usp=sharing

Made the report thumbnails rectangular for wide screens thinking they would resize to square (by cropping the sides) on narrower browsers. But let me know if you want them at a different size.

**Comment by kristinashu** [comment]
@cassiemc have you had a chance to look at the comps? https://redpen.io/p/opdb303c31041d13b6

**Comment by cassiemc** [comment]
This looks great guys. I might put a mozilla logo at the top, I think that'll lend credibility. And with the reports, do you want to include dates? Seems like an important contextual piece. @secretrobotron love your build so far, maybe you and @kristinashu can work on hover states and interactions. I think at the narrowest mobile size res the boxes should stack one on top of the other. Nice work everyone!

**Comment by secretrobotron** [comment]
:+1: @kristinashu what do you think those look like?

**Comment by secretrobotron** [comment]
Actually, @kristinashu: lmk if hover states on http://secretrobotron.github.io/research-website/ work.

**Comment by kristinashu** [comment]
Thanks @cassiemc! For the Mozilla logo, do you mean in addition to the tabzilla? I'll play around with adding dates in. 

@secretrobotron nice progress! That button hover works for me. Could you make it fade in a little tho? So it's a little smoother. 

Footer links can have the same hover states as thimble https://thimble.mozilla.org/

One nice-to-have-but-not-required transition would be if the banner text faded in like https://www.peer.com/

**Comment by cassiemc** [comment]
I've heard unofficially that tabzilla is getting discontinued so I just meant a little mozilla logo at the top centre.

**Comment by secretrobotron** [comment]
- [ ] fade in buttons
- [ ] fade in banner text
- [ ] footer hover states like thimble.mozilla.org
- [ ] real footer links
- [ ] real copy

**Comment by kristinashu** [comment]
Updated the 1170px wide desktop comp: https://redpen.io/p/opdb303c31041d13b6
- added report dates: font has same styling as buttons (medium weight 15px) but with 50% opacity
- updated footer links: here's an SVG for the flickr icon: https://drive.google.com/open?id=0B2irLVDJivhLdDBCNWtsdDZkUEk
- removed tabzilla and added mozilla logo: top right (tried center but it look odd over the girls head) with 50% transparency, hover state would have no transparency

Guess we'll also need a fav icon - we can use the same 'm' as on https://teach.mozilla.org/

**Comment by secretrobotron** [comment]
Super! Updated http://secretrobotron.github.io/research-website/ again. Only thing left is final copy. 

@cassiemc any more thoughts?

**Comment by kristinashu** [comment]
@secretrobotron photos don't seem to be loading for me? 

Also, noticed the button stroke looks a little pink, they should be white.

Are you going to do a mobile state as well?

**Comment by secretrobotron** [comment]
@kristinashu yeah, not sure why github decided not to host those images right now. Will probably be live in a few minutes.

What's the right colour for those buttons? I think I grabbed the rgb from your redpen.

I can do the mobile state, but I'm hesitating until a more competent CSS'er can help.

**Comment by kristinashu** [comment]
@secretrobotron the line should be white, it's super thin so it was probably hard to get the colour from JPG.

Lookin' good tho!

**Comment by secretrobotron** [comment]
Ah, great. Fixed. And images loading now (was totally my fault).

**Comment by kristinashu** [comment]
w00t images are loading!

**Comment by kristinashu** [comment]
P.S. fade in on page load is perfect!

**Comment by secretrobotron** [comment]
:dancer:

**Comment by kristinashu** [comment]
@secretrobotron since you're adding a gradient over the banner image through CSS (nice!) here's a version of the photo without the gradient added https://drive.google.com/open?id=0B2irLVDJivhLbXhEcUkwV2JJeTA

I think design is all done so I'm going to assign this ticket to you. But let me know if you need anything.

**Comment by secretrobotron** [comment]
Closing this now that build has started. Thanks @kristinashu :).
