### ISSUE TITLE
Make a repo for Unbox/NID/Hacktrain

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/research#107]
What should it be called?

**Comment by LauraReynal** [comment]
Actually, I propose that we make a repo for IoT in general. 
This will be used by the core team : you & I + @ileddigital + @thornet to track issues related to India, but also the IoT effort in EU.

We should think about india as part of something bigger. 

What do you think ?

**Comment by secretrobotron** [comment]
Yep. That's a great idea.

**Comment by secretrobotron** [comment]
https://github.com/MozillaFoundation/iot/
