### ISSUE TITLE
India - Design the graph for User Centered design

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#11]
@thisandagain @sabrinang 

Would you be able to make a design work for the India Report ? 
It goes with this text : 

*Iterative Design*
We used our Webmaker Prototype as a research approach in order to understand the participants better, but also to involve users at the center of our design. 
**Prototyping => Testing => Analyzing => Refining => Repeat**

*Innovation by Users*
We aim to meet a wide panel of participants to better understand who are our ‘Lead Users’ who might be using our product. We are also seek to discover who will not use Webmaker and why. From these interactions, we draw portraits, true stories from participants, in order to better understand who we design and innovate for. 

*Inspiration*
![ucd_new](https://cloud.githubusercontent.com/assets/8261945/6334693/43539508-bb8e-11e4-9b7f-f8e2d91a2e3a.gif)

**Comment by thisandagain** [comment]
Illustrator file in: `India > Illustrations > user_centered_design.ai`
![user_centered_design](https://cloud.githubusercontent.com/assets/747641/6495929/19b6447e-c283-11e4-9fec-d922f4646ed2.png)

**Comment by thisandagain** [comment]
Illustrator asset available at:
`India > Illustrations > iterative_design.ai`

![iterative_design](https://cloud.githubusercontent.com/assets/747641/6496009/b94a852c-c283-11e4-8dac-24a1fc4e5832.png)

**Comment by LauraReynal** [comment]
Thanks @thisandagain looks great !! :smile: :camel: :dromedary_camel: :dancers:
