### ISSUE TITLE
Add Jon To this repo

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#110]
@secretrobotron can you please add @ileddigital to this repo ? 
Huge thanks :tropical_fish:

**Comment by LauraReynal** [comment]
and @thornet

**Comment by secretrobotron** [comment]
No, I can't. Are you an admin on this repo?
Do you want them on this one, or shall we make another NID/Unbox/Hacktrain/Quicksand one?

**Comment by LauraReynal** [comment]
I think I managed to add them :smile: 
AND to make you an admin :cherries:
