### ISSUE TITLE
Brazil - Report revisions

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#12]
Continue work from https://github.com/MozillaFoundation/research/issues/4#issuecomment-75966988 including feedback from partners.

/cc @LauraReynal @benrito @thornet @soapdog

**Comment by LauraReynal** [comment]
Notes from our meeting : 
** @benrito @thornet @soapdog to submit comments about the report, any questions or suggestions. 
** Target publishing day is Friday 6th March

**Comment by LauraReynal** [comment]
Included comments from Constance in the Report 
Latest files are Rio20150304 

Waiting from @thornet and @benrito to submit comments if you have some ?

**Comment by LauraReynal** [comment]
Uploading the lates PDF here : https://www.dropbox.com/s/95smk3lh1cj3pb0/Rio20150304.pdf?dl=0

**Comment by LauraReynal** [comment]
@secretrobotron do you have time for a copy edit  on this report ?

**Comment by benrito** [comment]
I love this, it's my favorite of the reports.

Just a handful of suggestions:

Page 5:
Replace with revised paragraph: "For these reasons, Mozilla and Ford Foundation have initiated a community-centered digital inclusion project, experimenting with new models and helping Lan Houses to serve as sustainable digital making and learning spaces."

When possible avoid abbreviations on games:

GTA —> Grand Theft Auto
LoL —> League of Legends

Pluralization:

Lan Houses owners —> Lan House owners
each others —> each other
trainings centers —> training centers

Reclife —> is it Reclife or Recife?

Can we use a consistent punctuation when describing the capabilities of each house?
Seeing different punctuation as in 2mgh —> 2MBs 

cheers!

**Comment by LauraReynal** [comment]
Thank you @benrito -- Integrating and sharing asap !

**Comment by benrito** [comment]
Hey @LauraReynal what's the latest version? Is it ready for publication? No need to spend extra time, it's great already!

**Comment by secretrobotron** [comment]
Sorry: still on me to review. Can pay attention to it this week now that
Login project is rollin. External deadline?

**Comment by soapdog** [comment]
As soon as we have an ok on the English version I will update the Portuguese one

**Comment by benrito** [comment]
no crazy deadline but sooner we have it the more we add to project momentum

**Comment by LauraReynal** [comment]
Closing thanks to @secretrobotron :santa: :sparkles:
