### ISSUE TITLE
Chicago & London - Write new research proposal 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#14]
And review it, in order to start the planning :earth_americas:

**Comment by LauraReynal** [comment]
Hey @thisandagain @secretrobotron @adamlofting please review this Chicago-London proposal and add comments where you have questions. 

https://docs.google.com/a/mozilla.com/document/d/1lRY7nRxkhC9nYQKG3PpakppilKkuJNw_ve2-8CJA1Wc/edit?usp=sharing

**Comment by secretrobotron** [comment]
Tied to https://github.com/MozillaFoundation/plan/issues/368

**Comment by secretrobotron** [comment]
Some timing ideas:

This week: Commit to one or two "core team" people, and book flights to Chicago (and London, if possible)
March 17: Real heartbeat kickoff meeting to prepare for Chicago. Involve all the people that need to care.
March 31: Real heartbeat kickoff meeting to prepare for London. Involve all the people that need to care.

Two full heartbeats to assign people who are on that core team to help prepare, and two solid weeks of lead-up time before the trip starts.

**Comment by adamlofting** [comment]
Added some comments just now.

**Comment by LauraReynal** [comment]
The proposal have been submitted and reviewed. I added everyone's inputs in the document. Closing this ticket. Thanks everyone !
