### ISSUE TITLE
MWC - Design the "Pillars of an Open Mobile Internet"

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#15]
Hey @thisandagain could you do this sketch in our report style so as to include it in the MWC Synthesis?
I think it would really help clarify the message. Let me know if you have time, otherwise I will include it as such
![screen shot 2015-02-25 at 19 07 45](https://cloud.githubusercontent.com/assets/8261945/6378241/e11dc67a-bd21-11e4-98e8-334602de47e8.png)

**Comment by LauraReynal** [comment]
http://mitpressjournals.org/userimages/ContentEditor/1415302178306/INNOVATIONS_DIGITAL-INCLUSION.pdf 
Page 74 figure 5

**Comment by thisandagain** [comment]
:+1:

**Comment by LauraReynal** [comment]
Apparently not appropriate for this report. Closing. No more work needed. Sorry if you started
