### ISSUE TITLE
MWC - Research graphs

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#16]
Hey @thisandagain would you have time to make those graphs in our style guide plz? 
![screen shot 2015-02-25 at 20 52 17](https://cloud.githubusercontent.com/assets/8261945/6380264/4c5bb0d8-bd30-11e4-9be4-0869a7380cdc.png)

**Comment by LauraReynal** [comment]
![screen shot 2015-02-25 at 20 55 50](https://cloud.githubusercontent.com/assets/8261945/6380323/b6e72fb8-bd30-11e4-979f-5eb3b2f817cd.png)

**Comment by LauraReynal** [comment]
![screen shot 2015-02-26 at 16 42 26](https://cloud.githubusercontent.com/assets/8261945/6396468/85ef016e-bdd6-11e4-9557-a399f0c0a7fd.png)

**Comment by thisandagain** [comment]
Included in latest MWC report.
