### ISSUE TITLE
 Rio: localize initial report about Rio de Janeiro LAN houses 

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/research#17]
@soapdog has offered to localize the report into Brazilian Portuguese. He has InDesign and can do it once I have access to the original file. cc @LauraReynal 

Originally referenced in Mozilla-Learning repo https://github.com/MozillaFoundation/Mozilla-Learning/issues/95

**Comment by LauraReynal** [comment]
I gave @soapdog access to all the necessary files. 
Let me know if not okay.

**Comment by soapdog** [comment]
I am working on the translation. I am missing a Mozilla wordmark eps but this does not affect the work. I have one question though. Through the report there are many occurrences of the "Webmaker research" label/monicker, should I translate those or is it like a brand/team name that should remain in its English form?

**Comment by LauraReynal** [comment]
I would translate "research" since its not a brand name per say. We use this phrase a lot but its not a brand :smile:

**Comment by soapdog** [comment]
Thanks @LauraReynal! I will translate it.

Portuguese is much more wordy than English so phrases tend to take a lot more space. I am doing some wordsmithing here to use phrases that can fit. Thats one of the reasons why this is taking a bit longer than I wanted.

:smile:

**Comment by LauraReynal** [comment]
Hey @soapdog check your dropbox ! 
the Rio report has been updated with notes from ITS team 
Latest indesign file : Rio20150304 
Latest PDF file : Rio20150304
edits on the recommendation page - so it should not be too much trouble for you I hope !

**Comment by LauraReynal** [comment]
@soapdog can you keep your PT localized files in the same dropbbox folder, with the PT name in your doc please? It would help keep track and evaluate design work needed

**Comment by soapdog** [comment]
Will do @LauraReynal. I was keeping it in a non-Dropbox folder to avoid the net traffic of saving the file every couple seconds. I will move it there when I get back home.

**Comment by LauraReynal** [comment]
Hey @soapdog any news on this ?

**Comment by soapdog** [comment]
Its on Dropbox but I might have placed it on the wrong folder. Checking and getting back to you tonight.

**Comment by LauraReynal** [comment]
ok @soapdog let us know so we can close this, I dont have it in dropbox right now 
![screen shot 2015-03-27 at 14 23 43](https://cloud.githubusercontent.com/assets/8261945/6869546/e6e08bec-d48c-11e4-96be-2f0e8190db1c.png)

**Comment by soapdog** [comment]
@LauraReynal ,

I understand what happened. We both have folders for the report but they are not shared folders. You have a copy and I have a copy but they doesn't sync.

I've just shared my folder with you. Be aware not to overwrite your folder with mine because my English report file might be older than yours.

**Comment by soapdog** [comment]
Hi @LauraReynal can you change the email addresses to andre@mozillafoundation.org and mario@mozillafoundation.org on the contacts section, we finally got our LDAP working :-)

**Comment by LauraReynal** [comment]
@Soapdog - emails are updated :-)

Waiting for @secretrobotron copy review to publish.

Thanks !


*Laura de Reynal*
Webmaker - Field Research
@lau_nk <https://twitter.com/lau_nk>
Skype: laura-dereynal

**Comment by LauraReynal** [comment]
Hey folks, the report is published here mzl.la/rio and mzl.la/lanhouses so im closing this ticket !
