### ISSUE TITLE
Prepare new content for  build.wm.org

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#18]
Update the Audience page of build.wm.org with 
- Learning scenarios 
- Some indian personas 
- Updated Web Journey Graph

**Comment by LauraReynal** [comment]
cc @secretrobotron

**Comment by secretrobotron** [comment]
Tied to https://github.com/MozillaFoundation/plan/issues/368

**Comment by secretrobotron** [comment]
Tomorrow, let's chat about how we can prepare these so that they can go up on the site quickly.

**Comment by LauraReynal** [comment]
yes  - we need a game plan

**Comment by LauraReynal** [comment]
future to do list and brainstorming : 
- [ ] sketch new ideas for audience page 
- [ ] desing a the learning scenario 
cc/ @secretrobotron

**Comment by LauraReynal** [comment]
Tracking details in details in this issue : 
https://github.com/MozillaFoundation/plan/issues/373

**Comment by LauraReynal** [comment]
Closing this one since we are tracking in plan. Will file separate tickets for each item
