### ISSUE TITLE
[Build] Design the research map 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#19]
I have been mapping our research since day 1 with MapBox. For now, I have been using it as an offline tool, with screenshots of countries in the reports. 
Work Proposed: 
- It would be great to make a proper design of this map with our Webmaker branding.
- Create a set of icons for our participants groups (if possible?) eg. teachers, students, families ... 

Goal: 
Publish this map on audience and other sites, it is a powerful tool to show our work and tell our story, but today, not ready for wide publishing.

Any thoughts @secretrobotron @thisandagain ? Design resources available ?

**Comment by secretrobotron** [comment]
There should be design resources available, so long as we raise this up to TPS. With this and https://github.com/MozillaFoundation/research/issues/18 together, I think we should propose an "update audiences page" project for an upcoming heartbeat.

**Comment by secretrobotron** [comment]
Tied to https://github.com/MozillaFoundation/plan/issues/368

**Comment by secretrobotron** [comment]
p.s. did you already try doing something interactive, like google map maker?

**Comment by LauraReynal** [comment]
YEs Its fully interactive, I use Mapbox 
I can share a login and password to any designer willing to take a stab at it :)

https://a.tiles.mapbox.com/v4/jaggedzak.jp4e6n2d/page.html?access_token=pk.eyJ1IjoiamFnZ2VkemFrIiwiYSI6IlI3eHJ2WEUifQ.oH5KfF3KOu6X43-xdo2e2w#14/-22.9079/-43.2695

**Comment by LauraReynal** [comment]
Cc / @vazquez
