### ISSUE TITLE
India - Web Journey Illustration

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#2]

**Comment by LauraReynal** [comment]
@thisandagain would love to see our notes from Seattle, it would help me finalize the report. Thank you !

**Comment by thisandagain** [comment]
Yup! Will scan and add to this issue this evening when I get home.

**Comment by thisandagain** [comment]
Leaving here, but this really needs a pass through OmniGraffle to be understandable. Will do tomorrow AM.
![scan](https://cloud.githubusercontent.com/assets/747641/6261350/cdcca1b0-b7a2-11e4-8c75-4e05c20013ad.jpg)

**Comment by LauraReynal** [comment]
Thanks @thisandagain it's helpful already !

**Comment by thisandagain** [comment]
Assigned to self until I get the outline done.

**Comment by secretrobotron** [comment]
@thisandagain were you able to draw something up yesterday?

**Comment by cassiemc** [comment]
Pinging @iamjessklein to see if she can help. @secretrobotron can you connect with @iamjessklein and fill her in on what's needed?

**Comment by secretrobotron** [comment]
Totally. @iamjessklein : @thisandagain and @LauraReynal drew up a flow diagram to supplant the current Web Journey diagram (as seen at the bottom of http://build.webmaker.org/audience). We just need it to finish up this India report.

**Comment by thisandagain** [comment]
Added omnigraffle sketch on Dropbox:
![journey_20150306](https://cloud.githubusercontent.com/assets/747641/6537001/635c634e-c407-11e4-9d57-9bc5ffe9756b.png)

**Comment by secretrobotron** [comment]
This is excellent. @iamjessklein do you think you can take a stab at turning this into a diagram to replace the Web Journey one that's in the India report?

**Comment by iamjessklein** [comment]
@thisandagain @secretrobotron - it's unclear to me if this should be included in the graphic:

"The strongest initial motivators tend to be: "Fun", "Social / Peer", and "Attention" while both "Utility" and "Aspiration" appear more strongly as a user digs in deeper."

**Comment by iamjessklein** [comment]
Here's a first stab. [Please add comments on the invision mockup](http://invis.io/HZ2FFIJG3)
![journey](https://cloud.githubusercontent.com/assets/535012/6621473/38e2a146-c8ad-11e4-83e3-29905f9331f7.png)

cc/@secretrobotron

**Comment by thisandagain** [comment]
Looks good! A few small notes:
- We should imply some directionality from "Starting Conditions" to "Literacy". Right now it's a little easy to read the major progression as static / non-linear.
- Your 3rd column of dots (Capacity, Social, etc) seem to not be aligned vertically ... was this intentional? In addition, the spacing between points along a row seems to be inconsistent / arbitrary.
- Re: your earlier question. Having a gradient of motivations that drive people towards "literacy" at the bottom that change over time is what we are looking to communicate. A naïve idea to communicate that intent might be to show each motivator on the right with arrows pointing downwards that have different gradient values: utility & aspiration strongest towards creation and literacy while others are most strong at the beginning, etc.

**Comment by iamjessklein** [comment]
Here is a second attempt:

![letter](https://cloud.githubusercontent.com/assets/535012/6677094/47b61082-cc03-11e4-802f-e6aa68491d49.png)

**Comment by LauraReynal** [comment]
Hey @iamjessklein thanks for the progess ! A few notes : 

- Is there a way to emphasis the different states ? I think it is a bit confusing now, since there is a lot of text. 

- I noticed that there is an element missing before "starting conditions" => the "unaware" and "no use" states, which are quite important. Especially the "no use" . Both of these states require the 3 starting conditions. Also, conditions are requirement to start using, whereas the other dots are behaviours of people on the web, and for literacy, they represent skills 

- Right now "Starting conditions" is on the same design level as the other stages -> but its not a stage of the journey. This graphic matters because it shows people that there are still lots of people without access to the Web today, so IMO its important to leave the "unaware" and "no use" stages. 
another way to say it. 

What do you think ? 
![screen shot 2015-03-17 at 12 18 54](https://cloud.githubusercontent.com/assets/8261945/6687151/d5f38db0-cc9f-11e4-8569-862339c7f8df.png)

**Comment by iamjessklein** [comment]
:+1:  @LauraReynal and I talked offline and I am going to take another stab at this.

**Comment by LauraReynal** [comment]
Just pasting the latest here so we can keep track. Jess is currently working on an updated version. 

![screen shot 2015-03-18 at 16 26 47](https://cloud.githubusercontent.com/assets/8261945/6713625/9db6955e-cd8b-11e4-9cc2-b30f3ab7687b.png)

**Comment by thisandagain** [comment]
Incredible. Great work folks! :smile: :+1: :cat2: :cake: :boom:

**Comment by thisandagain** [comment]
To confirm, I'd like to have this integrated into the India report and have the published PDF updated by Friday EOD. Still do-able?

**Comment by LauraReynal** [comment]
Yay ! That was our plan :) we are just looking to see if we can add the motivators - maybe on the right 
Definitely published in the report by Friday

**Comment by LauraReynal** [comment]
Hey @iamjessklein 
My previous picture was not clear, so I am pasting this sketch here: 
2 notes : 
- After talking with people, we realised some important text had escaped. So I am re-inserting "Access + Capacity + need " which are *super* important => They are the 3 conditions for someone to be using the web
- Just wrote the motivators on the left, but feel free to insert them in another way if you prefer. 
![screen shot 2015-03-20 at 10 29 21](https://cloud.githubusercontent.com/assets/8261945/6749852/45d79d1c-ceec-11e4-9d95-908fbe224f26.png)

**Comment by cassiemc** [comment]
I'm confused about how this bug is critical but is listed as a p2 in https://github.com/MozillaFoundation/plan/issues/387. @secretrobotron ?

**Comment by secretrobotron** [comment]
@cassiemc it's remained critical from Feb 18. Didn't realize there was so much more work to be done on it. Probably should have been a P1.

**Comment by iamjessklein** [comment]
Here's another iteration - it incorporates:
* feedback from the design team
* new feedback from @LauraReynal 
* feedback already addressed on this ticket.

![webjourney-fri](https://cloud.githubusercontent.com/assets/535012/6755999/735372e6-cefd-11e4-908f-266906265d4d.png)

**Comment by LauraReynal** [comment]
I love it. To me this is good to go. 

GO? @thisandagain @secretrobotron ?

**Comment by secretrobotron** [comment]
:+1: ship

**Comment by iamjessklein** [comment]
@cassiemc just gave me some feedback. I am going to:

* cluster the "unaware" and "no use" personas in circles
* space out the elements

will not take me long.

**Comment by secretrobotron** [comment]
:+1: fix then ship

**Comment by cassiemc** [comment]
:+1: :zap:

**Comment by LauraReynal** [comment]
ok perfect @iamjessklein let me know and I can hit send :dancer:

**Comment by iamjessklein** [comment]
On redpen: https://redpen.io/p/pe0c3a8d2bb2253ccb

![journey-friday-v2](https://cloud.githubusercontent.com/assets/535012/6757429/5443c036-cf07-11e4-8116-b82d85521e6f.png)

**Comment by LauraReynal** [comment]
:heart: :heart: :heart: It's so great ! 
Can we ship ? 
@iamjessklein can you send me the file with a transparent background ? or white ? It'll be better on the report

**Comment by iamjessklein** [comment]
@LauraReynal I actually think that it looks best with a touch of light green behind it. I'll send the files.

**Comment by LauraReynal** [comment]
Oh ok no prob

**Comment by LauraReynal** [comment]
I am closing this ticket !!!!!! :fire: :fireworks: :dancer: :rose: 
Thank you so much Jess !

**Comment by secretrobotron** [comment]
Published on mzl.la/india
