### ISSUE TITLE
Research and desing work week ? Workshop ? 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#20]
@thisandagain @secretrobotron is this idea still alive? 

*Proposition*: Organise a workweek or design workshop to ideate on product solutions as well as curriculum ideas based on what we learned in all countries. Ideally it would gather folks from product and #teach. 

*Dates*: Could happen after London or after Chicago ?

**Comment by thisandagain** [comment]
Let's hold off on this until after the Chicago and London research. It's likely that we'll need another design meet-up at some point this year, but without a clear ask I don't see a need for this. cc @cassiemc
