### ISSUE TITLE
 Create a new metrics process for qualitative data

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#22]
Goal : Ensure we track the right metrics during our user research in Chicago and London, and define the process and the tools for collection. 

Phase: Research
Owner: @LauraReynal
with @adamlofting 
Decision: n/a
Lead design: n/a
Lead dev: n/a

To do 
- [x] Look at the metrics and the actual collection process 
- [x] Look at the tools used to collect
- [x] Create a dashboard

**Comment by adamlofting** [comment]
Let's work on the existing data for issue https://github.com/MozillaFoundation/research/issues/21 - then use that to inform this new metrics process.

**Comment by LauraReynal** [comment]
@adamlofting let's add this to our monday meeting
