### ISSUE TITLE
Bangladesh, Kenya, India: conduct desk research for quantitative data 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#23]
*Goal*: our existing research is purely qualitative and lacks numbers to back up our findings. 

*Action* : Search for exisiting work, surveys, reports etc with numbers which could back up our work. 
(example: QZ article on Internet = Facebook) 

RACI

Phase: Research 
Owner: @LauraReynal
Consulted: @cecilepompei 
Decision: @thisandagain 
Lead design: n/a
Lead dev: n/a
Quality: @thisandagain, @davidascher @benrito 

if you have any study in mind, you can paste the link in this issue ! Thanks

**Comment by cecilepompei** [comment]
Pour moi, ta recherche tu as des data aussi et tu peux utiliser ton sample
pour dire que TOI sur ta recherche, tu as trouve que
xx personnes pensait qu internet = facebook
que xx personnes avait des smart phones

etc etc

On Tue, Mar 3, 2015 at 9:40 PM, Laura de Reynal <notifications@github.com>
wrote:

> *Goal*: our existing research is purely qualitative and lacks numbers to
> back up our findings.
>
> *Action* : Search for exisiting work, surveys, reports etc with numbers
> which could back up our work.
> (example: QZ article on Internet = Facebook)
>
> RACI
>
> Phase: Research
> Owner: @LauraReynal <https://github.com/LauraReynal>
> Consulted: @cecilepompei <https://github.com/cecilepompei>
> Decision: @thisandagain <https://github.com/thisandagain>
> Lead design: n/a
> Lead dev: n/a
> Quality: @thisandagain <https://github.com/thisandagain>, @davidascher
> <https://github.com/davidascher> @benrito <https://github.com/benrito>
>
> if you have any study in mind, you can paste the link in this issue !
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/research/issues/23>.
>



-- 
Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by LauraReynal** [comment]
Thanks @cecilepompei I think you are referring to the other github ticket, where I am combining metrics from the existing research #21
