### ISSUE TITLE
Chicago - Imagine a new design workshop 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#27]
Similarly to the paper prototyping done in Bangladesh, Kenya and India, the goal is to come up with a series of design activities to help us understand better what people want to make and test our tinkerability ceiling. Will share ideas in this bug for feedback.

Consulted : @flukeout @secretrobotron @thisandagain @xmatthewx

**Comment by LauraReynal** [comment]
Pasting this here for reference 
https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c52d193c_2185

**Comment by LauraReynal** [comment]
Hey @flukeout @secretrobotron @thisandagain @xmatthewx @sabrinang 
Can you guys have a look at this and insert comments/ ideas ?
https://docs.google.com/a/mozillafoundation.org/document/d/1b9Bh9Lg72qBckhRdQHL-46xHcgm3oGEDciglswfBIoQ/edit#

**Comment by xmatthewx** [comment]
@LauraReynal - in [bit.ly/webmaker-build](http://bit.ly/webmaker-build), you'll find a section with easy links to the various prototypes starting on [this slide](https://docs.google.com/a/mozillafoundation.org/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gacde6376b_0_126).

They won't all be useful for testing, but might prompt some ideas.

**Comment by LauraReynal** [comment]
Thanks @xmatthewx
