### ISSUE TITLE
Rework the Threshold Diagram - and update the different reports 

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#3]

**Comment by LauraReynal** [comment]
![threshold kenya](https://cloud.githubusercontent.com/assets/8261945/6254035/8f2853f2-b773-11e4-9fac-479822fd0b52.png)
So we want to cut it for each "persona group"

**Comment by thisandagain** [comment]
Do you have the final list of persona groups for India? Do you want to stick with the same groupings as Kenya?

- Small Business Owners
- University Students
- High School Students
- Artists
- Teachers
- Journalists

**Comment by LauraReynal** [comment]
Let's keep the same for now. 
There is one more categorie for India = NGO worker
but I can fill it myself once there is a cut "template"

**Comment by thisandagain** [comment]
:+1:

**Comment by LauraReynal** [comment]
This is moved to backlog, and we'll do it **after MWC** :dancer: :dancers: :skull:

**Comment by LauraReynal** [comment]
Note from previous meeting : brainstorm ways of making this framework understandable by people. maybe a video or interactive design

**Comment by LauraReynal** [comment]
Note to self: Try to write the details for each cluster in a 3 lines paragraph to see if easier to read
