### ISSUE TITLE
Orange - finir proposal 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#34]
- [x]  Step 1 
- [x] step 2 
cc @cecilepompei

**Comment by LauraReynal** [comment]
This was a test issue for cecile - closing

**Comment by LauraReynal** [comment]
@cecilepompei

**Comment by cecilepompei** [comment]
super

On Mon, Mar 23, 2015 at 4:27 PM, Laura de Reynal <notifications@github.com>
wrote:

> @cecilepompei <https://github.com/cecilepompei>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/research/issues/34#issuecomment-85077017>
> .
>



-- 
Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115
