### ISSUE TITLE
Employability Research Proposal 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#37]
*Background*: @cecilepompei and @benrito are working on a proposal for Employability and Open Source contribution / Volunteering engagement

**Big Questions** : 
- If there a link between open source contribution / /volunteering at Mozilla  and employability ?
- What would people want from an organization like Mozilla  in order to start contributing?
- What would improve their employability level ? 

Areas of research
What we need to understand = what would be the motivators / constraints for youth to start contributing to Mozilla. 

1/ Motivators 
- Is there demand for certifications / what kind of certification ? 
- Certification => what kind of recognition would help youth get jobs
- Trainings // SKILLS => How / what / how long / select a few training areas and test them ( linked with George's work) What skills can we bring as Mozilla to young people ? (Running a Webmaker Club, Contributing to research, coding, etc)
- Community => does that matter ? / belonging / what would people expect from community belonging 
- Give back => Is it a motivator ? 
- Open Source => Mozilla's mission - Is there a difference between us and Google, Microsoft .. ? 

2/ Constraints 
- What would stop people from volunteering ?
- Constraints = What is refraining people today to engage ? Is lack of opportunity ? Resources ? 

---------

This research could happen in 2 countries - Tunisia and Ivory Coast ( Orange ) + Several other potential partners (south Africa, Zimbabwe) 

To do 
- [ ] Sync with George on his current work in Senegal
- [ ] Laura to write research details + budget => Light version and optimal version "Go fast and break walls" - Number of participants / detailed research questions / locations / activity planned / Deliverables / budget / ideal team composition 
- [ ] @cecilepompei  to choose countries  
- [ ] Cecile prepares the proposal and sends it 
- [ ] Next steps would be determined by the results of this proposal

**Comment by geroter** [comment]
Cool. What if we built this research into what is emerging as a strategy in Senegal? Basically, ask people as they are engaging with our community building there if employability is important, and then do some work to track employment outcomes?

**Comment by LauraReynal** [comment]
Hey Georges
Like the idea of embeding this plan into Senegal.
But if you only ask people who are already engaging with our community
building, then we would miss out on people who dont know us yet but could
be very keen on contributing. No ? I think we would need to answer both
questions.


*Laura de Reynal*
Webmaker - Field Research
@lau_nk <https://twitter.com/lau_nk>
Skype: laura-dereynal

**Comment by benrito** [comment]
What are the factors leaning us toward Tunisia and Ivory Coast among the Orange countries?

**Comment by benrito** [comment]
@geroter It's possible we can tap into help from Orange Foundation / CSR to integrate that into our plans. @cecilepompei can say more.

**Comment by cecilepompei** [comment]
Senegal - there are a few incubators that I have intros too so we could try
there
but Orange has a preference for the hubs in Tunisia (very dynamic and keen)
and Ivory Coast to try things

On Thu, Mar 26, 2015 at 7:51 PM, Ben Moskowitz <notifications@github.com>
wrote:

> @geroter <https://github.com/geroter> It's possible we can tap into help
> from Orange Foundation / CSR to integrate that into our plans.
> @cecilepompei <https://github.com/cecilepompei> can say more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/research/issues/37#issuecomment-86689083>
> .
>



-- 
Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by geroter** [comment]
Very small thing on this thread: People from Cote D'Ivoire get very annoyed with calling it Ivory Coast.

William and I are going to circle back with the broader plan early next week. This is an exciting collaboration that is shaping up between the teams, though.
