### ISSUE TITLE
Brazil - Finalize draft report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#4]

**Comment by LauraReynal** [comment]
The report is final, and shared with @benrito @thornet @thisandagain for a quick review before publishing. 
Let's track edits in this issue if possible?

https://www.dropbox.com/s/03vf4ltt6q7vp01/Rio2302.pdf?dl=0

![img_3271](https://cloud.githubusercontent.com/assets/8261945/6333585/297f8e3c-bb86-11e4-90d6-966d286c11b2.JPG)

**Comment by thisandagain** [comment]
Will do a pass on the graphic design of this tonight. Looks good thus far @LauraReynal

**Comment by benrito** [comment]
This doesn’t need to be published immediately, because we’ll want the Brazil team to manage the publication and communications around it. I think they’ll also have feedback.

If this is in current heartbeat, we can close as “Finalize v1" or kick into the next heartbeat. No rush here.

**Comment by thisandagain** [comment]
Works for me! Thanks @benrito
