### ISSUE TITLE
Reworking the web journey 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#40]
Goal : Needs a second pass on the web journey for the wider GSMA report and other works 

Owner : Laura 
Deisgn lead :  @lovegushwa 
Interested : @APLSmith @thisandagain @secretrobotron

**Comment by LauraReynal** [comment]
@sabrinang Lets keep track of our progress in this bug

**Comment by LauraReynal** [comment]
@sabrinang I'd like to consolidate "Unaware" and "unaware but no use" into a bigger one. As we did for creation and limited use. I will make update to the copy document. What do you think ?

ps: this drawing is just for me to structure and vizualise, feel free to continue iterate on your design ideas. It helped me see the different blocks.

**Comment by LauraReynal** [comment]
![webjourney v2 chicago](https://cloud.githubusercontent.com/assets/8261945/7361275/48f2a4b8-ed1b-11e4-83e5-02410759268e.jpg)

**Comment by LauraReynal** [comment]
cc /  @jgmac1106 and @thornet if you want to follow this bug ! Trying to add skills and constraints into the journey. But could not figure out where to add "Mentors" because it happens at each stage.

**Comment by LauraReynal** [comment]
@lovegushwa FYI the old iterations could be found here if needed #2 

Main improvements to make from that previous graphic are to 
- Add the different skills 
- Add the constraints somewhere if possible 
- Add some quotes 

I hope everything can fit. Let's chat today :koala: :dancer: :fire_engine: 

You can find the final copy here 
https://docs.google.com/a/mozilla.com/document/d/1r4ZW2Po0LYQaUdZ6VbCjlZg__lkH20TmH6Re2870L7k/edit?usp=sharing

cc / @thisandagain and @secretrobotron if you want to have a look on the content / copy

**Comment by lovegushwa** [comment]
@cassiemc @LauraReynal  R?
v3 of the web journey. 
![screen shot 2015-05-07 at 10 26 26 pm](https://cloud.githubusercontent.com/assets/12228435/7531096/4179b67c-f509-11e4-8da5-9b46cffb24f2.png)
You can see it becomes very information dense. @thisandagain suggested breaking the information out into several spreads. The diagram them morphed into a expand the visual language / evolve the typography and grid of the research reports.
![142-147](https://cloud.githubusercontent.com/assets/12228435/7531118/bd0dbce8-f509-11e4-8d92-eb3ad692e91b.jpg)
![142-1472](https://cloud.githubusercontent.com/assets/12228435/7531120/c225c432-f509-11e4-9061-2f8829b5e191.jpg)
![142-1473](https://cloud.githubusercontent.com/assets/12228435/7531122/c6120920-f509-11e4-87d9-3be0bbd46b0c.jpg)
Changes to the document type styles are very subtle. Changes in point size, leading, margin tweaks, small cap style that you maybe cant see but should be an improvement overall. The spreads are totally a WIP (work in progress.) What do you think?

A note on the other assigned bits:
I need to jump on the threshold diagram #39 tomorrow to finish a draft by end of day. 
Content for Chicago - Design a day in the life of teen timeline #48 is not available yet.

**Comment by LauraReynal** [comment]
Hey Jordan, 
Thanks for sharing the progress. I love the way you break the information into several spreads. It might be a really good approach to keep the reader engaged in this framework for a few pages before jumping into the text explanations that will come right after. 
I believe its the right approach to let it soak :+1: 

About the design, 
- I like the way the skeleton of the framework is built on top of a picture, it is really immersed in the report that way as opposed to pasting a graphic we could have found elsewhere on the web. :+1: 

- I have more doubts about the cropping of the pictures on the spreads, on top of the gradient. I would rather use the pictures in a more powerfull way (in your face) or not at all, maybe it's worth thinking about it with the goal of bringing empathy, and allowing the reader to relate to that person- which is the goal of the quote. 

On a more general note, I always think about these reports in a storytelling / magazine approach, which is why they have so many pictures. 
Let me know if I can help, or if looking for other type of comments 
thanks ! :camel:

**Comment by secretrobotron** [comment]
These look great! I actually enjoy the "dense" version as an infographic, since I expect to read through the flow of one of those slowly and carefully. Would love to use that on the audience page (cc @LauraReynal).

The middle section of the broken-out versions is a bit hard to read/follow. Not sure the gradient(s) present flow properly. Is the point of this section to showcase quotes and sentiments? I'd love to see something a bit cleaner, like the first section.

**Comment by cassiemc** [comment]
Hope you don't mind I added these to redpens so I could leave specific comments. @lovegushwa you should have upload powers to that redpen project if you want to update anything there. https://redpen.io/p/sg7caaf3615c984b04 

Overall I really like the idea of breaking up the dense graph and spreading quotes throughout, I think that's successful. The small type looks cleaner, but the header type and layouts and styles could use some simplifying. One way to think of the challenge here is to have a large version of the graph for the main explanation, then a small simplified version of the graph for the pics & quotes pages so you can refer back to the stages of the graph. One large, one small and inset, kind of thing.

I left a number of comments about language as well @LauraReynal. Keep it up guys, nice work :)

**Comment by lovegushwa** [comment]
Thanks @cassiemc  @secretrobotron  @LauraReynal for the great critical input! I'm about the bike into the office, printing these out at scale will help me incorporate feedback.

**Comment by LauraReynal** [comment]
Hey @lovegushwa Could we close this ? 
Let me know where the file is and if you think it needs more work ? 
Thanks !

**Comment by lovegushwa** [comment]
@LauraReynal 
I uploaded the current version here: 
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvUEdMdHRlNFU1Zzg&usp=sharing

Check out the template, we can work together to simplify it if needed.
