### ISSUE TITLE
India - Complete draft of report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#5]

**Comment by LauraReynal** [comment]
Made progress. 90% done. 
Still needs a bit of work in one weak part.

**Comment by LauraReynal** [comment]
The content of the report is finalized:
- Added Appendix 
* participants scope 
* research locations
* design workshops 
- Added a few quotes 
- Added a page about Webmaker (same as Bangladesh report )
- Streamlined the Portraits structured 
- finalized a persona that was missing 
.... I think its good, let me know if you see Content problems 
cc @thisandagain 
Closing this issue

**Comment by thisandagain** [comment]
Yay! Thanks @LauraReynal
