### ISSUE TITLE
Finalize Maker Party Activities

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#56]
Goal : Publish 2 activities for Webmaker and Maker Party 

1. One activity must be offline 
2. The other one must be on the phone 

- [x]  Laura to make the activity 1 Offline
- [ ]  Laura to make the activity 2
- [ ] @secretrobotron will put them on github 
- [ ] @amirad will review and publish

**Comment by LauraReynal** [comment]
FRIENDS ! 

I just finished to write the activity for offline creation / design here : https://docs.google.com/document/d/1MnKa_frV0grPE_DqfKzRuoYBinUZ3acQ4ac7Rq08nUk/edit# 

It's very much based on the design workshops I have been doing but I remixed it for a MP audience - so let me know if its too long - too short etc. For example, I did not treat this a curriculum, and it does not have a lot of "Let's learn about URLS" but more about designing and structuring a story. 
Katie's curriculum has a lot more on learning, so I did not want to do a double.

Anyway - let me know - @secretrobotron you can start coding :smile: 

@amirad I have an important questions: Are these activities meant to be used separately  ? or is it one after the other ? If so I would need to remix activity 2 to be purely on mobile with no paper at all. Let me know

**Comment by amirad** [comment]
Beauty! @secretrobotron can you get this into github by end of week as well? I'll start reviewing it now. 

@LauraReynal They can be used together or separately but I'm assuming people will pick one or the other based on resources/access/phones etc.

**Comment by LauraReynal** [comment]
I think we can close this  - Let me know if needs to be re-open @secretrobotron @amirad 
Thanks !
