### ISSUE TITLE
Finalize the Digital Skills Observatory proposal 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#57]
Goal: finalize the proposal for the Digital Skills Observatory project

Deadline : Thursday 23rd 

Team: @metaphorista @benrito @thisandagain @lauraReynal

Some details to do : 

- [x] Refine plan with DDD - questions in this pad https://foundation.etherpad.mozilla.org/QuestionsforDDD-20Digital-20Skills-20Observatory
- [x] Scope the volunteers roles and work implied (trainings, on-boarding etc) 
- [x] Scope the curriculum work (how much will be needed, with what frequency, resources etc)
- [x] Scope assesment methods - How do we know if this project is successful ?
- [x] Create estimate planning 
- [x] Create estimate budget

**Comment by LauraReynal** [comment]
Working document https://docs.google.com/document/d/1IsU2Ms6IBCj0mNpNzTZK6ZOwPa7kLIgpgLDPExxcyeY/edit#heading=h.j0f3thr8farn

**Comment by LauraReynal** [comment]
To add in the organizational sections:

- metrics about volunteers and events, example MozfestEA
- other research studies

**Comment by LauraReynal** [comment]
To do 
- [ ] remix Dnet Case Study graphic 
- [ ] Make timeline

**Comment by LauraReynal** [comment]
@metaphorista Here is the graphic for the methods - Let me know if this is what we talked about. 

@benrito @thisandagain can you check the content please ? 

- We mentioned that we would introduce 2 prototypes and so I coupled them with trainings on Q2 and Q3. Realistic ? 

- We did not set up a frequency for trainings, but I made a tentative for monthly, and then, we can add more if needed. This is written in the document: participants are likely to benefit from on demand trainings. 

- Are you okay with having coms in here as part of the research methods or is it making the image too heavy ?

NB: This is not a project managment timeline and does not take into account every details since the project is not finalize, but simply tries to summarize research methods for clarification purposes. 

![gates - digital skills observatory - new page](https://cloud.githubusercontent.com/assets/8261945/8806955/9861a322-2fd9-11e5-8ae7-ea39edbc6c0b.png)

**Comment by benrito** [comment]
This is an excellent graphic; couple thoughts:

•rather than monthly, we might opt for a visual that says "continuous"
"transparent" documentation
•maybe put a box around that and the workshop piece and label "increase
understanding among other stakeholders working in digital inclusion and
DFS" or something
•we might want an accompanying graphic for how we will cultivate the
trainers
•will be curious to see Michelle's feedback

Cheers!
Ben

**Comment by LauraReynal** [comment]
Thanks for the feedback Ben, 
- ok for the continous coms
- ok for the workshop label 
- yes ! im working on the volunteer part on a separate doc / graph 
- Will ping Michelle to ask feedback on this method.

Below is an updated version including feedback from the design team. 

![gates - digital skills observatory - new page 1](https://cloud.githubusercontent.com/assets/8261945/8812331/bc9ecd1a-2ffb-11e5-9979-f77264dfdff9.png)

**Comment by LauraReynal** [comment]
Proposal submitted :sparkles:
