### ISSUE TITLE
India - Finalize report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#6]
Blocked by #5

**Comment by LauraReynal** [comment]
Hey @sabrinang I made good progress on the Indian report transfert to indesgin
you will find in our dropbox a doc called **INDIA_2302** in the india folder. 

I have reached until 'Basic Use' and will continue tomorrow, but you can still start and edit the first 47 pages if you want :smile: 

Aslo if you are inspired, feel free to copy / paste the content from here.
https://docs.google.com/document/d/1dc9dn7qaes-6quetYd8-cPqouPcUbJU8SQiBLS6M7hs/edit?usp=sharing

**Comment by LauraReynal** [comment]
Hey @sabrinang @thisandagain 
The India Report is ready for a design pass
The document is called 24_02
thanks

**Comment by thisandagain** [comment]
@LauraReynal will take another pass this evening. Will ping you on Skype once I'm ready.

**Comment by LauraReynal** [comment]
@thisandagain the report is ready for a design pass. There should not be any more pages or modifications, aside from a couple sentences here and there after re-reading all.

**Comment by LauraReynal** [comment]
The doc is still named 24_02

**Comment by LauraReynal** [comment]
:warning: Actually better if you can work on 25_02 document if you have not started yet. This way there is a copy somewhere. :bow: :tulip:

**Comment by LauraReynal** [comment]
Hey @thisandagain I think we should find a way to show the Web Journey Graph each time we move to a new stage in the document. Otherwise it might be difficult for the reader to follow along: we know the graph by heart but not them.

**Comment by LauraReynal** [comment]
I'm thinking instead of the double page picture I put before each new stage, we could have one picture on the left and the graph on the right. Thoughts?

**Comment by LauraReynal** [comment]
@secretrobotron Does a grammar pass by Wednesday latest
I will input comments by thursday EOD 
Publishing date - Friday

**Comment by LauraReynal** [comment]
@secretrobotron we need a designer to do the UCD graph from #11 do you know who we can ask?

**Comment by secretrobotron** [comment]
@LauraReynal : still on @thisandagain's plate. Should be done tomorrow AM.

**Comment by LauraReynal** [comment]
@secretrobotron huge thanks for the millions of comments :smile: :jack_o_lantern: :japanese_castle: :princess: :rabbit: :fire: :ghost: 

I have edited until page 99 ! Will finish tomorrow. 
The latest file is 20150305. 

-----
A few notes from your notes
- Cover page : the date indicates when the work was executed, not published. We did like this for the 2 previous ones, but I agree it might seem odd.
- p.12 : when footnotes are blue and underlined, they are links. Do you suggest something else?

- p.23 : teledensity Do you really think it needs a definition ? I don’t know if you are kidding or not because there is a smiley. 

- p24: you did not make a note on this page, but I just noticed it is really weird to have this title: **Triggers/ What could enable people to move to “no use” ?**
=> Seems odd that we would want people to move to a “no use” state. What we really mean, is move to “aware”. But it would mean changing the wording, which is tricky. Thoughts?

- p.36 => Women don’t go online => Replace “this exclusion” with “self-imposed exclusion” ==> I disagree with your suggestion, because it is not self-imposed most of the time, it is mandatory, obeying rules and normes from a community, or a husband, or a brother. Or a mother. They are not **allowed** to go online, i.e. they are *excluded*, not *self-excluded*. 
okay for you ? 

- p. 60 = I added a sentence on Veena, last paragraph (the tech part was weak).
- p. 64 = leaving English Medium School capitalised, as it seems to be the way ( I verified online + saw it there).

**Comment by secretrobotron** [comment]
> Cover page : the date indicates when the work was executed, not published

:+1: 

> p. 12 : when footnotes are blue and underlined, they are links.

Just wanted to make sure that they actually go somewhere. They weren't links in my PDF (I couldn't click on them).

> p.23 : teledensity Do you really think it needs a definition?

Unless it's something that people who will read this report routinely use, then yeah, define it. I've never seen it before. It's jargon.

> p.24 : Seems odd that we would want people to move to a “no use” state.

Agreed. How about "What could enable people to progress from being "unaware"?" Then, you imply that they could wind up at any stage along the journey.

> p.36 : Replace “this exclusion” with “self-imposed exclusion”

:+1: yeah, totally. By "self-imposed", I meant that *society* does it to itself. But, you're right: confusing. Leave it the way it was.

> p. 60 = I added a sentence on Veena,

I don't see it. Can you re-publish the PDF?

> p. 64 = leaving English Medium School capitalised

:+1: just make sure that the other places you use "XXXXX Medium School" are consistent with that

**Comment by secretrobotron** [comment]
:candy: :whale:

**Comment by LauraReynal** [comment]
thanks !! :rose: :space_invader: 

- Links : this is bad, because I thought they were hyperlinks. I will figure out the problem and update them all then, 
- Teledensity: ok will define in footnote 
- p.24 -> perfect suggestion :sparkler: 
- New PDF is published, make sure you use the 20150305 :yum:

**Comment by secretrobotron** [comment]
For those links: let me double-check too. It could just be the software I'm using because... software.

**Comment by LauraReynal** [comment]
@secretrobotron :fish: :rabbit: :whale: 
Edits are complete and new PDF is in the dropbox. Named 20150306. 
Latest inDesign file is also 20150306. 

:warning: I have not figured out the link problem
Here is what I did for each: 
![screen shot 2015-03-06 at 11 54 59](https://cloud.githubusercontent.com/assets/8261945/6524238/c23d381c-c3f7-11e4-885c-6b14f3731d39.png)

@thisandagain do you know if it is a PDF preset problem ? I use the "flower and sparkles" preset we made together. I used the web to find solution but did not seem to uncover the problem. 
Thanks for your help.

**Comment by cassiemc** [comment]
@LauraReynal  are you exporting as an interactive PDF? I dont have the latest version of indesign but I suspect the problem would be in your export or pdf options rather than in the link panel.

**Comment by LauraReynal** [comment]
@cassiemc I tried , but still isnt clicking ! :crying_cat_face:

**Comment by cassiemc** [comment]
Can you screenshot your flow for saving out?

**Comment by secretrobotron** [comment]
@cassiemc I can share the `indd` file if you're able to help export it.

**Comment by LauraReynal** [comment]
HEy @cassiemc here is the file for older versions of indesign, but the last time i saved it like this for Ben, all links were broken... so let me know, otherwise see you in your vidyo soon :)

https://www.dropbox.com/s/a82ghiyzpabuygo/INDIA_20150306.idml?dl=0

**Comment by cassiemc** [comment]
I exported the file as an Interactive pdf and was able to see links in both Preview and Acrobat (I was testing the footnote links on page 18). Here's the file I exported: https://www.dropbox.com/s/yauutu3glkxavn3/india-test-cassie.pdf?dl=0 The linked images are wonky so you can't use this as a final export, but the hyperlinks are fine.

**Comment by LauraReynal** [comment]
thanks @cassiemc for your help. 
A few more changes and we are shipping.

**Comment by thisandagain** [comment]
Now up at http://mzl.la/india

**Comment by LauraReynal** [comment]
HUGE thanks :100: :x: :100:  @secretrobotron @thisandagain  for all the help ! 
:boat: :fish: :cocktail: :cat2: :jack_o_lantern: :candy: :dancer: :dart: 

cc/ @davidascher @benrito -- Report published

**Comment by davidascher** [comment]
nice. Long haul, good to get it out the door!
