### ISSUE TITLE
Research hub

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/research#64]
Is there a single page with links to all the research reports? If not, let's make it. A wiki in this repo would work. A page on build dot Webmaker would be even nicer. 

@Timboliu is looking for links.

**Comment by LauraReynal** [comment]
Thanks @xmatthewx I am making a wiki page - In the meanwhile, I have this http://lauradereynal.com/research-reports/

I'll let you know when the wiki is done

**Comment by Timboliu** [comment]
In which research can I find information about people don't want to create applications? When I open the research of India. I see on the first page that people want to create applications.

**Comment by LauraReynal** [comment]
Each of the reports have stories and analysis about people who dont want to create, people who dont know about the web etc. 
We have studied a variety of behaviors and they should be represented in each reports.

**Comment by Timboliu** [comment]
Hi Laura,

When I read the stories I see indeed that a lot of people don't have much experience with the web. But if WebMaker just wants to be a simple CMS for the mobile phone (is this true?) how does WebMaker differ from WordPress? And another trend I see is that laptops and PC's are becomming cheaper. How long will it take that the next wave of internet users have bigger screens, a keyboard and a mouse?

My intention with this message is to start a discussion about the future of WebMaker. I really love the first version, but I don't understand the direction WebMaker wants to go in the future.

Regards,

Tim

**Comment by jgmac1106** [comment]
Hey @Timboliu I am a volunteer contributor to many of the MLN products so I am sharing my perspective and not so much "official canon" First using the  words simple and wordpress together should never happen. I am a college professor working with may first generation college students who have been online most of their lives. Even they get overwhelmed by WP. 

Trying to introduce a complicated mobile CMS to people who have never been online would be hard. 

I also might argue, and @LauraReynal's data bare this out that for many people in emerging economies are skipping PCs and going mobile only. The future is mobile first. If you read the [roadmap](https://docs.google.com/spreadsheets/d/1ZvdNJLHuW0fIBt_-WcR7Ns6OhZgaMy6MI9kfjlXF-9o/edit#gid=0) you will see a desktop version is coming.

Webmaker is designed to get people writing the web and not just reading in social networks silos. Hopefully as these new users begin to write the web they will want to peak under the hood and remix code.

**Comment by Timboliu** [comment]
Hi Greg,

Thanks for your insight and the link to the roadmap.

Regards,

Tim

**Comment by Timboliu** [comment]
Is it possible to share information about user activity on WebMaker? And I have another question: I understand that Webmaker focuses on 'first-time-users'. How quickly does Mozilla expect these users will learn and want more options? Does Mozilla want these users to stick with Webmaker? Or is the purpose of Webmaker that these users try other CMS's?

**Comment by cassiemc** [comment]
@Timboliu I'd suggest this isn't the right issue for discussing the future of Webmaker. Try https://github.com/mozilla/webmaker-core/issues

I'm going to close this issue because it is covered by https://github.com/MozillaFoundation/plan/issues/553
