### ISSUE TITLE
To do for Indonesia Research 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#66]
- [x] Get visa letters from Angela (Bobby)
- [x] Budget approval (Laura)
- [x] Get a little bit of cash (Bobby)
- [x] Get tons of cash (Laura)

---------

- [x] Refine locations planning 
- [x] Book Jakarta accommodation (Bobby)
- [x] Book Jakarta accommodation (Laura)
- [x] Book Surabaya accommodation (Bobby)
- [x] Book Surabaya accommodation (Laura)
- [x] Book Surabaya accommodation (Ina and Rara)
- [x] Book Jakarta to Surabaya
- [x] Book Surabaya to Makassar
- [x] Book Makassar to Jakarta
- [x] Jakarta accomodation for the last days (Bobby)
- [x] Jakarta accomodation for the last days (Laura)

------
### Scheduling and recruiting
- [x] Prepare intro email for recruiting participants 
- [ ] Recruit participants for interviews 
- [ ] Recruit participants for design workshops 
- [ ] Send shoutout on FB/Telegram to IDN Mozillians to meet up in Jakarta.

--------

### For the FIELD
- [ ] prepare participants profiles 
- [ ] print participants profiles 
- [ ] Plan interview questions 
- [ ] prepare design workshops 
- [ ] get material for design workshops 
- [ ] Get Telkomsel SIMs (Red one) x2 
- [ ] get a sort of prototype of the website from Sabrina
- [ ] Decide incentives for participants (butttons ? Gift cards ?)

**Comment by LauraReynal** [comment]
- [ ] Recruit participants for interviews 
- [ ] Recruit participants for design workshops 
- [ ] plan interview questions

**Comment by secretrobotron** [comment]
Apparently, for Canadian citizens, a work (meetings) visa is attainable upon entrance to country for $35 USD: http://www.kemlu.go.id/toronto/Pages/InformationSheet.aspx?IDP=17&l=id&l=id

**Comment by secretrobotron** [comment]
Advice from everyone: stay in Kosenda hotel in Jakarta.

**Comment by LauraReynal** [comment]
- [ ] Prepare intro email for recruiting participants

**Comment by LauraReynal** [comment]
FIELD TO DO 
- [ ] prepare participants profiles 
- [ ] print participants profiles 
- [ ] prepare design workshops 
- [ ] get material for design workshops

**Comment by LauraReynal** [comment]
I wrote 2 intro emails for indonesia here https://etherpad.mozilla.org/introemail

**Comment by LauraReynal** [comment]
Purchasing trip Jakarta to Surabaya - 3 people / 4 people

**Comment by LauraReynal** [comment]
rara to send budget  for mozcoffee

**Comment by LauraReynal** [comment]
help the team with swag

**Comment by LauraReynal** [comment]
I completed the budget for the Indonesia part 
submitting for approval asap

**Comment by LauraReynal** [comment]
- [ ] send laura ID + phone numbers for intra country flights @alamanda @rara79

**Comment by secretrobotron** [comment]
Send shoutout on FB/Telegram to IDN Mozillians to meet up in Jakarta.

**Comment by secretrobotron** [comment]
- [ ] Get Telkomsel SIMs

**Comment by rara79** [comment]
Venue confirmed for MozKopdarMKS (MozCoffee Makassar): Kedai Pojok Adhyaksa, Oct 4th.

**Comment by LauraReynal** [comment]
Here is a scratch pad for product questions https://docs.google.com/document/d/12LgqqHNYmOuMy-fJfjb_98-trtlPx_evDNU41AxWReE/edit#

**Comment by LauraReynal** [comment]
Hey @alamanda @rara79 what is the name of the hotel we should book for Surabaya ? I forgot

**Comment by LauraReynal** [comment]
-  @amirad do you have the contact of the Regional coordinator for the Indonesia clubs?

- @alamanda @rara79 do you know the community members who are leading the clubs in Indonesia ? https://teach.mozilla.org/clubs/ 
We need to make sure we talk to the club captains.

- @secretrobotron do you have a list of the people who have been running a Webmaker event ? Is there anyone to talk to specifically ?

cc / @williamq @cecilepompei  do you have specific people that you recomend we meet when we go to indonesia ? Especially looking for people outside of the community as well. Any org , NGO we should meet ?

**Comment by rara79** [comment]
@LauraReynal hotel in Surabaya is Santika Premiere. 

@Alamanda and @eriskatp are the Regional Coordinator for Mozilla Club in Indonesia. 

Also, you will meet the rest of Webmaker Launch Team in the Sept 29th event :)

**Comment by alamanda** [comment]
Venue confirmed for MozCoffe/Community Meetup/Focus group discussion: Domicile Kitchen 
http://domicile-sby.com/about/index

**Comment by alamanda** [comment]
In Sept 29th, you'll meet with at least 3 of the Mozilla Club Captains in Indonesia.

**Comment by amirad** [comment]
@LauraReynal our RCs are the lovely @alamanda and Eriska (eriskaprimaya@gmail.com)

**Comment by LauraReynal** [comment]
Everything on this list is done - Closing ! thanks everyone for the help
