### ISSUE TITLE
Publish pictures from Indonesia on a google drive and on flickr

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/research#79]
- [x] make a google drive folder
- [x] put images from Indonesia in that folder (Laura)
- [x] put Webmaker launch stuff in that folder (Bobby)

**Comment by secretrobotron** [comment]
Boom.

**Comment by secretrobotron** [comment]
@LauraReynal do designers know about this folder?

**Comment by secretrobotron** [comment]
cc @KevZawacki @HPaulJohnson @lovegushwa @cassiemc ?

**Comment by cassiemc** [comment]
Not sure that they do! From design team perspective, best thing might be to share the folder in Design Assets > Assets > (new photos folder), and include a readme link to the flickr page? https://drive.google.com/a/mozilla.com/folderview?id=0ByIoeeW0a3R_STBRYnYzTTJvVkk&usp=sharing

We could also just link from the Design Assets folder to a research one, if stuff is already there. Designers are currently wrestling with space/capacity issues on Drive.

**Comment by KevZawacki** [comment]
These could be useful to the social teams here and at MoCo. @secretrobotron is there a gallery I can share with them?

**Comment by LauraReynal** [comment]
I use flickr a lot for people to view and download images. The gallery here has all the research pictures organized by albums, and the indonesia ones are here too.

Albums for each trip  https://www.flickr.com/photos/laura_nk/albums/with/72157662503996752 
Indonesia https://www.flickr.com/photos/laura_nk/albums/72157662503996752

**Comment by LauraReynal** [comment]
Let me know if there is anything to do. I think @lovegushwa has been putting pictures somewhere else on drive, but I cant find it

**Comment by KevZawacki** [comment]
@LauraReynal Perfect, thanks!

**Comment by secretrobotron** [comment]
@KevZawacki @cassiemc here's the Indonesia stuff: https://drive.google.com/a/mozilla.com/folderview?id=0B-7F6kqkuFwdVE01RFNMd010UFE&usp=sharing

**Comment by cassiemc** [comment]
Thanks @secretrobotron! I filed a new issue in the design repo, as I don't think photo sharing has been properly tackled yet. https://github.com/MozillaFoundation/Design/issues/124
