### ISSUE TITLE
India - Publish report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/research#8]
- [x] @LauraReynal writes draft blog post and submit to @KevZawacki
- [x] @secretrobotron or @KevZawacki does copy edits 
- [x] @LauraReynal writes a blog post
- [ ] @secretrobotron and @KevZawacki check blog post
- [x] @LauraReynal posts on M4D blog and Webmaker blog
- [x] @secretrobotron links to pdf on webmaker.org/localweb and hosts on www.mzl.la/india
- [ ] @LauraReynal sends to all mofo

*Edited by secretrobotron on March 3: Added todo list*

**Comment by LauraReynal** [comment]
To do: 
- Laura writes draft blog post and submit to @kevinzawacki 
- Kevin does copy edits
- Laura posts on M4D blog and Webmaker blog 
- Laura sends to all mofo

**Comment by KevZawacki** [comment]
cc @HPaulJohnson

**Comment by LauraReynal** [comment]
Hey @KevZawacki @HPaulJohnson @secretrobotron 

Here is a draft blog post for publishing the india report: 
https://m4d.etherpad.mozilla.org/BangladeshReport

Ideally we would be able to publish this by EOD, or monday the latest. We are still waiting for a 1% of work on the report itself, but are ready for your input ! 
Thanks

**Comment by secretrobotron** [comment]
@KevZawacki @edrushka I've done a pass on @LauraReynal's blog post. Should be good to ship as long as you don't find anything egregious.

**Comment by KevZawacki** [comment]
@secretrobotron @edrushka @HPaulJohnson @LauraReynal 

Just finished my copy edits. You can find latest on Google Docs: http://goo.gl/3RTJhh

We're just missing the Research Map and link to the report.

**Comment by LauraReynal** [comment]
The blog post is ready. Now we need the report ready and then I'll hit publish :)

**Comment by LauraReynal** [comment]
Hey guys ! blog post published here https://blog.mozilla.org/m4d/2015/03/06/india-research/
Thanks for all your help !
