### ISSUE TITLE
Prepare slide deck to present NID and Kenya

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/research#83]
- [x] build slide deck to talk about NID and Kenya
- [ ] send to MoFos
- [ ] talk about it on demo call
- [ ] schedule a MoFo-oriented brownbag to talk about it
- [ ] talk on Mozilla project call
- [ ] schedule a talk/session/something in Orlando

**Comment by LauraReynal** [comment]
Did you get a chance to see when is an appropriate time to talk to Mofos from David ?

**Comment by LauraReynal** [comment]
The slide deck is finished. Closing this. we can prob present in Orlando
