### ISSUE TITLE
Build plan for working with participation team

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/research#84]
- [x] schedule chat with participation folks
- [x] share our plans now, discover their plans for next year
- [ ] work on a joint plan (what is that?)
- [ ] meet in orlando to talk about making it happen?

**Comment by LauraReynal** [comment]
I think we can close this. 
We shared the plans with them, now we need to keep them posted on the regular progress and start the process of recruiting volunteers from our side.
