### ISSUE TITLE
[PM] Budget for IoT projects = EU + India 

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/research#87]
Make sure budget is defined, finalized and approved.

Need to figure out how it connects to wider IoT project.

Details on page 12
: https://docs.google.com/document/d/18JkDK5TiFXG_ZMLkJ84HQxX1aX6zGmZKsYOMjQFrGpc/edit#

**Comment by secretrobotron** [comment]
@davidascher can you add details wrt how this budget connects to wider IoT project? Need to expand the budget? If so, how?

**Comment by LauraReynal** [comment]
Checking on budget today during our call w/ jon
