### ISSUE TITLE
Make research email address

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/research#96]
@secretrobotron do you know how to have an email address for anyone to write to us ?
Ideally, this would go to you+adam+I 
We can replace my email on the reports with this address. 

I filed a ticket a while ago, but research@mozilla.org is already taken.

- 1: should we get research@mozillafoundation.org ?
- 2: is there a way that it does not spam us like mobileopportunity or explorers lists ?

**Comment by secretrobotron** [comment]
What kind of spam do you get from the mobileopportunity/explorer lists? I got a lot of messages from explorers because it was a mailing list for which people just kept signing up. Did you get any actual spam?

**Comment by LauraReynal** [comment]
Can we make it a list that is just for us or does it have to be a list that people sign up for ?

**Comment by secretrobotron** [comment]
Ordered research[at]mozillafoundation.org as an alias. Easiest for now.

**Comment by secretrobotron** [comment]
Done. Should go to @LauraReynal, @adamlofting and me.
